export default ['-请选择-', '俄罗斯', '伊朗', '日本', '韩国', '沙特阿拉伯', '澳大利亚', '比利时', '德国', '英格兰', '西班牙', '波兰', '冰岛', '塞尔维亚', '葡萄牙', '法国', '瑞士', '克罗地亚', '瑞典', '丹麦', '巴西', '乌拉圭', '阿根廷', '哥伦比亚', '秘鲁', '墨西哥', '哥斯达黎加', '巴拿马', '尼日利亚', '埃及', '塞内加尔', '摩洛哥', '突尼斯'];

export const flag =  {'俄罗斯':require('./img/Russia.png'), 
'伊朗':require('./img/Islami.png'), 
'日本':require('./img/japan.png'), 
'韩国':require('./img/keroa.png'), 
'沙特阿拉伯':require('./img/Arabia.png'),
'澳大利亚':require('./img/Australia.png'), 
'比利时':require('./img/Belgien.png'), 
'德国':require('./img/Germany.png'),
'英格兰' :require('./img/england.png'),
'西班牙' :require('./img/Spain.png'), 
'波兰':require('./img/Poland.png'),  
'冰岛':require('./img/island.png'), 
'塞尔维亚':require('./img/Serbia.png'), 
'葡萄牙':require('./img/Portuguesa.png'), 
'法国':require('./img/French.jpg'), 
'瑞士' :require('./img/Switzerland.png'),
'克罗地亚':require( './img/Croatia.png'),
 '瑞典':require('./img/Sweden.png'),
 '丹麦':require('./img/Denmark.png'), 
 '巴西':require('./img/Brasil.png'), 
 '乌拉圭':require('./img/Uruguay.png'),  
 '阿根廷':require('./img/Argentina.png'), 
 '哥伦比亚':require('./img/Colombia.png'),
 '秘鲁':require('./img/Peru.png'), 
 '墨西哥':require('./img/Mexico.png'), 
 '哥斯达黎加':require('./img/CostaRica.jpg'),
 '巴拿马' :require('./img/Panama.png'), 
 '尼日利亚':require('./img/Nigeria.png'),
 '埃及' :require('./img/Egypt.png'), 
 '塞内加尔':require('./img/Senegal.png'), 
 '摩洛哥':require('./img/Morocco.png'), 
 '突尼斯':require('./img/Tunisia.png')};
