export default [{ name: '-请选择-' }, { name: '--小组赛--' }, { name: '-A组-' },
{ num: 1, name: '俄罗斯vs沙特阿拉伯' },
{ num: 2, name: '埃及vs乌拉圭' },
{ num: 17, name: '俄罗斯vs埃及' },
{ num: 19, name: '乌拉圭vs沙特阿拉伯' },
{ num: 33, name: '乌拉圭vs俄罗斯' },
{ num: 34, name: '沙特阿拉伯vs埃及' },
{ name: '-B组-' },
{ num: 3, name: '摩洛哥vs伊朗' },
{ num: 4, name: '葡萄牙vs西班牙' },
{ num: 18, name: '葡萄牙vs摩洛哥' },
{ num: 20, name: '伊朗vs西班牙' },
{ num: 35, name: '伊朗vs葡萄牙' },
{ num: 36, name: '西班牙vs摩洛哥' },
{ name: '-C组-' },
{ num: 5, name: '法国vs澳大利亚' },
{ num: 7, name: '秘鲁vs丹麦' },
{ num: 21, name: '丹麦vs澳大利亚' },
{ num: 22, name: '法国vs秘鲁' },
{ num: 37, name: '丹麦vs法国' },
{ num: 38, name: '澳大利亚vs秘鲁' },
{ name: '-D组-' },
{ num: 6, name: '阿根廷vs冰岛' },
{ num: 8, name: '克罗地亚vs尼日利亚' },
{ num: 23, name: '阿根廷vs克罗地亚' },
{ num: 25, name: '尼日利亚vs冰岛' },
{ num: 39, name: '尼日利亚vs阿根廷' },
{ num: 40, name: '冰岛vs克罗地亚' },
{ name: '-E组-' },
{ num: 9, name: '哥斯达黎加vs塞尔维亚' },
{ num: 11, name: '巴西vs瑞士' },
{ num: 24, name: '巴西vs哥斯达黎加' },
{ num: 26, name: '塞尔维亚vs瑞士' },
{ num: 43, name: '塞尔维亚vs巴西' },
{ num: 44, name: '瑞士vs哥斯达黎加' },
{ name: '-F组-' },
{ num: 10, name: '德国vs墨西哥' },
{ num: 12, name: '瑞典vs韩国' },
{ num: 28, name: '韩国vs墨西哥' },
{ num: 29, name: '德国vs瑞典' },
{ num: 41, name: '韩国vs德国' },
{ num: 42, name: '墨西哥vs瑞典' },
{ name: '-G组-' },
{ num: 13, name: '比利时vs巴拿马' },
{ num: 14, name: '突尼斯vs英格兰' },
{ num: 27, name: '比利时vs突尼斯' },
{ num: 30, name: '英格兰vs巴拿马' },
{ num: 47, name: '英格兰vs比利时' },
{ num: 48, name: '巴拿马vs突尼斯' },
{ name: '-H组-' },
{ num: 15, name: '哥伦比亚vs日本' },
{ num: 16, name: '波兰vs塞内加尔' },
{ num: 31, name: '日本vs塞内加尔' },
{ num: 32, name: '波兰vs哥伦比亚' },
{ num: 45, name: '日本vs波兰' },
{ num: 46, name: '塞内加尔vs哥伦比亚' }
];